### PR TITLE
feat: use v1.9.2 of jcasbin

### PR DESCRIPTION
**Pull request by shink**

### CODE REVIEW

**Comment by fangzhengjin** [comment]
@shink plz fix this error

**Comment by hsluoyz** [comment]
@shink plz fix:

image

**Comment by shink** [comment]
@fangzhengjin @hsluoyz The error was caused by the conflict between slf4j and logback, so I excluded slf4j in jcasbin. Is this okay?

**Comment by fangzhengjin** [comment]
> @fangzhengjin @hsluoyz The error was caused by the conflict between slf4j and logback, so I excluded slf4j in jcasbin. Is this okay?

If SLF4J is excluded only in Casbin-Spring-Boot-Starter, then users still have this problem when using.

**Review by fangzhengjin — APPROVED** [review]

**Pull request merged**
