### PR TITLE
FilteredPolicy for JdbcAdapter.

### PR DESCRIPTION
**Pull request by shy1st**
FilteredPolicy for JdbcAdapter.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@shy1st plz fix the checks

image

**Comment by hsluoyz** [comment]
@fangzhengjin please review.

**Comment by fangzhengjin** [comment]
@shy1st JdbcAdapter is a singleton object. When using the internal variable isFiltered, it may be modified by other threads. Should we use a read-write lock in the method of using the isFiltered variable to prevent this from happening?

**Review by hsluoyz — CHANGES_REQUESTED** [review]
Please merge all commits into a single one.

**Comment by shy1st** [comment]
> @shy1st JdbcAdapter is a singleton object. When using the internal variable isFiltered, it may be modified by other threads. Should we use a read-write lock in the method of using the isFiltered variable to prevent this from happening?
> Please merge all commits into a single one.

@fangzhengjin Thanks for your advice，I will fix it.

**Comment by fangzhengjin** [comment]
@shy1st Please do not submit changes to the src/test/resources/application.yml file, and you also need to submit some unit tests to verify that the current code is running as expected.

**Comment by shy1st** [comment]
> @shy1st Please do not submit changes to the src/test/resources/application.yml file, and you also need to submit some unit tests to verify that the current code is running as expected.

@fangzhengjin Thanks for your advice，I will deal with it.

**Comment by hsluoyz** [comment]
@fangzhengjin can you please help see why CI failed?

**Comment by fangzhengjin** [comment]
@shy1st It seems that the adapter is not injected in the test case, please try to inject using adapter interface instead of JdbcAdapter.

**Comment by fangzhengjin** [comment]
My current equipment is not convenient for local debugging. Let me check it with my computer on Monday.

**Comment by shy1st** [comment]
> My current equipment is not convenient for local debugging. Let me check it with my computer on Monday.

@fangzhengjin  sorry to trouble you.

**Review by fangzhengjin — APPROVED** [review]

**Comment by fangzhengjin** [comment]
LGTM

**Comment by fangzhengjin** [comment]
fix #16

**Pull request merged**
