### PR TITLE
Add the "id" column for the table "casbin_rule".

### LINKED ISSUE #21: no ‘id’ in casbin rule?
Coming from this issue: https://github.com/node-casbin/sequelize-adapter/issues/38

Hi,

Currently most of the casbin adapter casbin_rule table had added an ‘id’ column as the primary key. Could you please tell is it capable for this project to add back the ‘id’ column? Thanks a lot.

### PR DESCRIPTION
**Pull request by shy1st**
Fix: https://github.com/jcasbin/casbin-spring-boot-starter/issues/21

### CODE REVIEW

**Comment by hsluoyz** [comment]
@fangzhengjin please review.

**Comment by hsluoyz** [comment]
@wy10cheng @daiyueliang plz review.

**Review by fangzhengjin — COMMENTED** [review]
Should we consider checking the existing database and adding the id field to allow users of the old version to upgrade without hindrance?
Or do we issue an announcement on the impact of the upgrade?

**Comment by Moon-86** [comment]
Sorry,Could you also update casbin-spring-boot-starter.jar in maven repository ?
Thank you

**Comment by fangzhengjin** [comment]
> Sorry,Could you also update casbin-spring-boot-starter.jar in maven repository ?
> Thank you

I do not understand what you mean.

**Comment by Moon-86** [comment]
> > Sorry,Could you also update casbin-spring-boot-starter.jar in maven repository ?
> > Thank you
> 
> I do not understand what you mean.

https://mvnrepository.com/artifact/org.casbin/casbin-spring-boot-starter
⇧Sorry,here don't need update?

**Comment by fangzhengjin** [comment]
> > > Sorry,Could you also update casbin-spring-boot-starter.jar in maven repository ?
> > > Thank you
> > 
> > 
> > I do not understand what you mean.
> 
> https://mvnrepository.com/artifact/org.casbin/casbin-spring-boot-starter
> ⇧Sorry,here don't need update?

Need to update, but does this have anything to do with the issue we are discussing now?

**Comment by hsluoyz** [comment]
> Should we consider checking the existing database and adding the id field to allow users of the old version to upgrade without hindrance?
> Or do we issue an announcement on the impact of the upgrade?

@shy1st whether do you think we need it?

**Comment by shy1st** [comment]
> > Should we consider checking the existing database and adding the id field to allow users of the old version to upgrade without hindrance?
> > Or do we issue an announcement on the impact of the upgrade?
> 
> @shy1st whether do you think we need it?

I think we don't need it. We can issue an announcement on the impact of the upgrade.

**Comment by hsluoyz** [comment]
@shy1st plz make a Maven & GitHub Release (or we can use your new semantic-release feature)

**Comment by shy1st** [comment]
Excuse me,could you tell me what command you usually use to release the version to the maven repository for this project? @fangzhengjin

**Comment by fangzhengjin** [comment]
> Excuse me,could you tell me what command you usually use to release the version to the maven repository for this project? @fangzhengjin

Modify the version_code in the gradle.properties file and tag it. After Travis is built, it will be published to bintray, and then you need to log in to bintray to synchronize to MavenCenter.


> > > Excuse me,could you tell me what command you usually use to release the version to the maven repository for this project? @fangzhengjin
> > 
> > 
> > Modify the version_code in the gradle.properties file and tag it. After Travis is built, it will be published to bintray, and then you need to log in to bintray to synchronize to MavenCenter.
> 
> Thanks.

Try not to mark when you have not modified the version_code, because it may overwrite the build of the previous version of bintray.

**Comment by shy1st** [comment]
> > 请问，您能告诉我通常使用什么命令将该版本发布到该项目的Maven存储库吗？@fangzhengjin
> 
> 修改gradle.properties文件中的version_code并对其进行标记。创建Travis后，它将被发布到Bintray，然后您需要登录到Bintray才能同步到MavenCenter。

Thanks.

**Comment by hsluoyz** [comment]
@shy1st plz use English. Actually I don't know why the quoted content becomes Chinese :)

**Comment by shy1st** [comment]
> > Excuse me,could you tell me what command you usually use to release the version to the maven repository for this project? @fangzhengjin
> 
> Modify the version_code in the gradle.properties file and tag it. After Travis is built, it will be published to bintray, and then you need to log in to bintray to synchronize to MavenCenter.

Thanks.

**Comment by shy1st** [comment]
> @shy1st plz use English. Actually I don't know why the quoted content becomes Chinese :)

Sorry, it was a mistake.

**Pull request merged**
