### PR TITLE
fix: db2 adapter issue

### LINKED ISSUE #47: DB2Adapter can not work after adding id for the casbin_rule table
The DB2Adapter doesn't work after adding id for the casbin table via this PR: https://github.com/jcasbin/casbin-spring-boot-starter/pull/24/files . It caused by wrong initial sql statement. I will fix it later.

### PR DESCRIPTION
**Pull request by doctormacky**
Fix: https://github.com/jcasbin/casbin-spring-boot-starter/issues/47

### CODE REVIEW

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/jcasbin/casbin-spring-boot-starter/pull/48

**Comment by hsluoyz** [comment]
@doctormacky plz don't open multiple PRs. You can do anything like rewriting commits in the same PR.

**Comment by doctormacky** [comment]
> @doctormacky plz don't open multiple PRs. You can do anything like rewriting commits in the same PR.

Hi @hsluoyz I am sorry for that, seems there are some format checking, including singed-off, and also the PR name rerstiction. So, just have some try on that, Yeah, I was planing to remove the duplicate one.

**Comment by seriouszyx** [comment]
LGTM for the fix. 
But it seems the node version in CI env is so old that semantic-release can not work. 
image
Could you update it to node16? Simply change [this line](https://github.com/jcasbin/casbin-spring-boot-starter/blob/5220c75761ba5a06840e85b9d1f8ee4111473a82/.github/workflows/gradle-ci.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L49).

**Comment by hsluoyz** [comment]
@seriouszyx good finding!

**Pull request merged**
